[package]
name = "dirtcrunch"
authors = ["Tejas Sanap<sanap.tejas@gmail.com>"]
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
shiplift = "0.7.0"
futures = "0.3.17"
tokio = { version = "1.12.0", features = ["macros"] }
